use_random_feature: false
use_lru_feature: false
use_lfu_feature: false
use_ogd_lru_feature: false
use_ogd_lfu_feature: false
use_ogd_opt_feature: false
use_bert_feature: false
swf_w_lens:
  - 1     #10s
  - 6     #1min
  - 30    #5min
  - 60    #10min
  - 180   #30min
  - 360   #1h
  - 720   #2h
  - 1440  #4h
  - 2880  #8h
  - 8640  #1d
  - 17280 #2d
  - 25920 #3d
  - 34560 #4d
  - 43200 #5d
  - 51840 #6d
  - 60480 #7d
