use_random_feature: false
use_lru_feature: false
use_lfu_feature: false
use_ogd_lru_feature: false
use_ogd_lfu_feature: false
use_ogd_opt_feature: false
use_bert_feature: false
swf_w_lens:
  - 6     #1min
  - 30    #5min
  - 60    #10min
  - 180   #30min
