#- [ RlCacheRunner,{ kd_mode: 5 } ]
- [ RlCacheRunner,{ kd_mode: 4 } ]
#- [ RlCacheRunner,{ kd_mode: 3 } ]
#- [ RlCacheRunner,{ kd_mode: 2 } ]
- [ RlCacheRunner,{ kd_mode: 1 } ]
- [ RlCacheRunner,{ kd_mode: 0 } ]
- [ LruCacheRunner,{ } ]
- [ LfuCacheRunner,{ } ]
- [ OgdOptCacheRunner,{ } ]