- [ RlCacheRunner,{ kd_mode: 2 } ]
- [ RlCacheRunner,{ kd_mode: 1, eager_mode: True } ]
- [ RlCacheRunner,{ kd_mode: 0 } ]
- [ LruCacheRunner,{ } ]
- [ LfuCacheRunner,{ } ]
- [ OgdOptCacheRunner,{ } ]