name: zipf_1.2_dynamic_2m_0.33_0.33_2_iid
time_beg: 0
time_end: 2000000
time_int: 10
info: "zipf_dynamic_2m_0.33_0.33_2_iid"
data_path:
  - asserts/data/zipf/1.2/dynamic_2m_0.33_0.33_2/iid/0.csv
  - asserts/data/zipf/1.2/dynamic_2m_0.33_0.33_2/iid/1.csv
  - asserts/data/zipf/1.2/dynamic_2m_0.33_0.33_2/iid/2.csv