capacity: 10
verbose: true
log_id: "0092"
comm_size: 4
data_permute: false
data_config: "iqiyi_pois.yaml"
feature_config: "drl.yaml"
runner_config: "ewdrl_single.yaml"

agent_config:
  class_name: "EWDNN"
  hidden_layer_units:
    - 256
    - 32
  memory_size: 5000
  batch_size: 128
kd_config:
  interval: 5
  k: -3
