capacity:
  - 10
  - 20
  - 30
  - 40
  - 30
  - 20
  - 40
data_config: "iqiyi12.yaml"
feature_config: "drl.yaml"
runner_config: "ewdrl_kd.yaml"

agent_config:
  class_name: "EWDNN"
  hidden_layer_units:
    - 256
    - 32
  memory_size: 5000
  batch_size: 64

kd_config:
#  class_name: SoftKDCallback
  interval: 20

# kdw_lr: 3e-4
# min_entropy_ratio: 0.8
# kwd_log_tau

log_id: "1096"
comm_size: 7
data_permute: false
n_neighbors: 4
