capacity: 10

data_config: "iqiyi_pois.yaml"
feature_config: "drl.yaml"
runner_config: "ewdrl_kd2.yaml"

comm_size: 7
data_permute: false

agent_config:
  class_name: "EWDNN"
  hidden_layer_units:
    - 256
    - 128
  memory_size: 5000
  batch_size: 128

kd_config:
#  class_name: SoftKDCallback
  interval: 20

log_id: "2081"
n_neighbors: 0
sparsity: 1.0
load_weights: True
tmp_save: True