capacity: 10

data_config: "iqiyi_pois.yaml"
feature_config: "drl.yaml"
runner_config: "ewdrl_single.yaml"

comm_size: 1

agent_config:
  class_name: "EWDNN"
  hidden_layer_units:
    - 256
    - 32
  memory_size: 5000
  batch_size: 64
kd_config:
  class_name: SoftKDCallback
  interval: 20

data_permute: false
log_id: "0301"
sparsity: 1.0