capacity:
  - 10
  - 20
  - 30
  - 40
  - 30
  - 20
  - 40
log_id: "0095"
comm_size: 1
data_permute: false
data_config: "iqiyi12.yaml"
feature_config: "drl.yaml"
runner_config: "ewdrl_kd_different_capacity.yaml"

agent_config:
  class_name: "EWDQN"
  hidden_layer_units:
    - 256
    - 32
  memory_size: 5000
  batch_size: 64
kd_config:
  interval: 20
n_neighbors: -4
