capacity: 10

data_config: "iqiyi12.yaml"
feature_config: "drl.yaml"
runner_config: "ewdrl_kd2.yaml"

comm_size: 8

agent_config:
  class_name: "EWDNN"
  hidden_layer_units:
    - 128
    - 32
  memory_size: 5000
  batch_size: 128

kd_config:
#  class_name: SoftKDCallback
  interval: 20

log_id: "3050"
weights_id: "0003"
n_neighbors: 3
sparsity: 0.9
data_permute: True
load_weights: True
tmp_save: True