capacity: 20
data_config: "iqiyi12.yaml"
feature_config: "drl.yaml"
runner_config: "ewdrl_kd.yaml"

comm_size: 8
data_permute: true

agent_config:
  class_name: "EWDNN"
  hidden_layer_units:
    - 256
    - 32
  memory_size: 5000
  batch_size: 64
kd_config:
#  class_name: SoftKDCallback
  interval: 20

log_id: "1000"
n_neighbors: 4
sparsity: 1.0
eager_mode: False

