capacity: 10

data_config: "iqiyi_pois.yaml"
feature_config: "drl.yaml"
runner_config: "ewdrl_single_kd.yaml"

comm_size: 1
data_permute: false

agent_config:
  class_name: "EWDNN"
  hidden_layer_units:
    - 256
    - 32
  memory_size: 5000
  batch_size: 64
kd_config:
  class_name: SoftKDCallback
  interval: 20

log_id: "0302"
sparsity: 0.9
