capacity:
  - 10
  - 15
  - 20
  - 25
  - 25
  - 20
  - 15
  - 10
data_config: "iqiyi12.yaml"
feature_config: "drl.yaml"
runner_config: "ewdrl_kd2.yaml"

agent_config:
  class_name: "EWDNN"
  hidden_layer_units:
    - 256
    - 128
  memory_size: 2000
  batch_size: 64

kd_config:
#  class_name: SoftKDCallback
  interval: 20

log_id: "20055"
comm_size: 8
data_permute: True
n_neighbors: 4
sparsity: 1.0