capacity: 50
verbose: false
data_config: "iqiyi12.yaml"
feature_config: "drl.yaml"
runner_config: "ewdrl_kd.yaml"

log_id: "0050"
comm_size: 8
data_permute: true

agent_config:
  class_name: "EWDNN"
  hidden_layer_units:
    - 256
    - 32
callback_config:
  kd_config:
    class_name: HardKDCallback
    interval: 5
