capacity:
  - 10
  - 15
  - 20
  - 25
  - 25
  - 20
  - 15
  - 10
data_config: "iqiyi_pois.yaml"
feature_config: "drl.yaml"
runner_config: "ewdrl_kd2.yaml"

agent_config:
  class_name: "EWDNN"
  hidden_layer_units:
    - 256
    - 128
  memory_size: 5000
  batch_size: 128

kd_config:
  #  class_name: SoftKDCallback
  interval: 20

# kdw_lr: 3e-4
# min_entropy_ratio: 0.8
# kwd_log_tau

log_id: "50002"
comm_size: 7
data_permute: false
n_neighbors: 4
