capacity: 100
verbose: false
log_id: "0062"
comm_size: 7
data_permute: false
data_config: "iqiyi_pois.yaml"
feature_config: "drl.yaml"
runner_config: "ewdrl_kd.yaml"

agent_config:
  class_name: "EWDNN"
  hidden_layer_units:
    - 256
    - 32
  memory_size: 5000
  batch_size: 128
kd_config:
  interval: 20
  k: 3
#  mode: 1
