capacity:
  - 10
  - 20
  - 30
  - 40
  - 30
  - 20
  - 40
data_config: "iqiyi12.yaml"
feature_config: "drl.yaml"
runner_config: "ewdrl_kd.yaml"

agent_config:
  class_name: "EWDNN"
  hidden_layer_units:
    - 256
    - 128
  memory_size: 5000
  batch_size: 128

kd_config:
#  class_name: SoftKDCallback
  interval: 20

log_id: "20000"
comm_size: 8
data_permute: false
n_neighbors: 4
