capacity: 10

data_config: "zipf_1.2_dynamic_10.yaml"
feature_config: "drl.yaml"
runner_config: "ewdrl_kd.yaml"

comm_size: 8
data_permute: true

agent_config:
  class_name: "EWDNN"
  hidden_layer_units:
    - 256
    - 128
  memory_size: 5000
  batch_size: 128

kd_config:
#  class_name: SoftKDCallback
  interval: 20

log_id: "8001"
n_neighbors: 0
sparsity: 1.0