capacity: 10
verbose: true
log_id: "0000"
comm_size: 1
data_permute: true
data_config: "iqiyi_pois.yaml"
feature_config: "drl.yaml"
runner_config: "ewdrl_single.yaml"

agent_config:
  class_name: "EWDNN"
  hidden_layer_units:
    - 32
    - 8
  memory_size: 5000
  batch_size: 128
kd_config:
  interval: 20
  k: 0
