capacity: 10
verbose: false
data_config: "iqiyi12.yaml"
feature_config: "drl.yaml"
runner_config: "ewdrl_kd.yaml"

log_id: "0007"
comm_size: 12
data_permute: true

agent_config:
  class_name: "EWDNN"
  hidden_layer_units:
    - 256
    - 32
  log_tau: -7
  log_tau_clip: [ -10, 1 ]
  min_entropy_ratio: 0.0001
  memory_size: 50000
  batch_size: 4096
  use_kl_div_loss: True
  update_tau_freq: 5
callback_config:
  kd_config:
    class_name: HardKDCallback2
    interval: 5
